<?php defined('ABSPATH') || exit;

/**
 * Yoast SEO Integration and Customizations
 *
 * @version 2.7.0
 */

// =============================================================================
// YOAST SEO FILTER CONFIGURATIONS
// =============================================================================

/**
 * Disable Yoast SEO automatic redirect features
 *
 * Prevents automatic redirects when post or term slugs are changed. Disabled because
 * redirects are handled through other mechanisms or to maintain access to both old and new URLs.
 */
add_filter('Yoast\WP\SEO\post_redirect_slug_change', '__return_true');
add_filter('Yoast\WP\SEO\term_redirect_slug_change', '__return_true');

// =============================================================================
// CANONICAL URL CUSTOMIZATIONS
// =============================================================================

/**
 * Modify canonical URL for paginated WooCommerce shop pages
 *
 * Fixes SEO issue where paginated shop pages would have their own canonical URLs,
 * potentially causing duplicate content issues. Ensures all paginated shop pages
 * have the main shop page as their canonical URL.
 *
 * Workaround for when Yoast SEO backend settings don't work properly for WooCommerce shop pages.
 *
 * @param string $canonical The original canonical URL generated by Yoast SEO
 * @return string Modified canonical URL for shop pages, original URL for other pages
 */
function yoast_seo_canonical_change_woocom_shop($canonical) {
    if (!is_shop()) {
        return $canonical;
    }

    if (is_shop() && is_paged()) {
        $shop_url = wc_get_page_id('shop');
        if ($shop_url && $shop_url > 0) {
            return get_permalink($shop_url);
        }
    }
    return $canonical;
}
add_filter('wpseo_canonical', 'yoast_seo_canonical_change_woocom_shop', 20, 1);
